### ISSUE TITLE
initial release tracking

### ISSUE THREAD

**Issue by kleinschmidt** [beacon-biosignals/StandardizedPredictors.jl#5]
We're spinning off our implementation of standardized regression predictors and releasing it to the community. Hooray! Here's what needs to happen:

Task list
- [x] Make this tracking issue :) 
- [x] No private info in code 
- [x] Pre-make public commit:
  - [x] Add MIT license
  - [x] Add tests + CI badge to README
 - [x] Make sure repo follows best-practice settings
   -  [X] Make docs build #1 
   - [x] Add docs badges to README #1 
   - [x] Add TagBot GitHub Action
   - [x] Add CompatHelper GitHub Action
- [x] Clean up printing #9 
- [x] Make repo public
- [x] Have @jrevels enable repo access for the general julia registrator
- [x] Open [PR in Julia registry]() 
  - [x] Wait for it to auto-merge
